Traceback (most recent call last):
  File "/Users/ggeorg02/opt/miniconda3/envs/bait580envtestbug/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/ggeorg02/opt/miniconda3/envs/bait580envtestbug/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ggeorg02/opt/miniconda3/envs/bait580envtestbug/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ggeorg02/opt/miniconda3/envs/bait580envtestbug/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/ggeorg02/opt/miniconda3/envs/bait580envtestbug/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/ggeorg02/opt/miniconda3/envs/bait580envtestbug/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/ggeorg02/opt/miniconda3/envs/bait580envtestbug/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%%time
%%sql
explain analyze SELECT nasdaqsymbol, ROUND(change / open, 2), COUNT(*) AS tweets
               FROM tweets.dtwide 
        WHERE retweet = 'FALSE' AND nasdaqsymbol = 'BABA'
        GROUP BY day, nasdaqsymbol, change, open;
------------------

----- stdout -----
 * postgresql://postgres:***@database-2.ch0m6kus6nrp.us-east-1.rds.amazonaws.com:5432/postgres
----- stdout -----
17 rows affected.
CPU times: user 11.7 ms, sys: 5.6 ms, total: 17.3 ms
Wall time: 14.8 s
------------------

Traceback [0;36m(most recent call last)[0m:

[0m  File [1;32m~/opt/miniconda3/envs/bait580envtestbug/lib/python3.12/site-packages/IPython/core/interactiveshell.py:3553[0m in [1;35mrun_code[0m
    exec(code_obj, self.user_global_ns, self.user_ns)[0m

[0m  Cell [1;32mIn[6], line 1[0m
    get_ipython().run_cell_magic('time', '', "%%sql\nexplain analyze SELECT nasdaqsymbol, ROUND(change / open, 2), COUNT(*) AS tweets\n               FROM tweets.dtwide \n        WHERE retweet = 'FALSE' AND nasdaqsymbol = 'BABA'\n        GROUP BY day, nasdaqsymbol, change, open;\n")[0m

[0m  File [1;32m~/opt/miniconda3/envs/bait580envtestbug/lib/python3.12/site-packages/IPython/core/interactiveshell.py:2523[0m in [1;35mrun_cell_magic[0m
    if DisplayHook.semicolon_at_end_of_expression(cell):[0m

[0m  File [1;32m~/opt/miniconda3/envs/bait580envtestbug/lib/python3.12/site-packages/IPython/core/displayhook.py:101[0m in [1;35msemicolon_at_end_of_expression[0m
    tokens = list(tokenize.generate_tokens(sio.readline))[0m

[0m  File [1;32m~/opt/miniconda3/envs/bait580envtestbug/lib/python3.12/tokenize.py:541[0m in [1;35m_generate_tokens_from_c_tokenizer[0m
    raise e from None[0m

[0;36m  File [0;32m~/opt/miniconda3/envs/bait580envtestbug/lib/python3.12/tokenize.py:537[0;36m in [0;35m_generate_tokens_from_c_tokenizer[0;36m
[0;31m    for info in it:[0;36m

[0;36m  File [0;32m<string>:4[0;36m[0m
[0;31m    WHERE retweet = 'FALSE' AND nasdaqsymbol = 'BABA'[0m
[0m                                                     ^[0m
[0;31mIndentationError[0m[0;31m:[0m unindent does not match any outer indentation level


